import 'package:flutter/material.dart';
import 'package:mandobi_mobile_app/Utils/color_utils.dart';
import 'package:mandobi_mobile_app/Utils/extensions.dart';
import 'package:mandobi_mobile_app/Utils/font_sizes.dart';
import 'package:mandobi_mobile_app/Utils/font_utils.dart';

class TermsOfUseText extends StatelessWidget {
  const TermsOfUseText({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Text(
      """
"These terms and conditions of use ("Terms") cover your use and access to Mandobi Application and its associated services and content (collectively "Application"), provided by Mandobi and any of our affiliates. By accessing and using the Application you agree to be bound by these Terms as well as our Privacy Policy.
    You may use the Application only if you have the right and legal capacity to enter into this agreement and to adhere to the Terms. You warrant that you are a human individual that is the legal age of majority in your state of residence (but not less than 18 years of age) and that you are not a bot, script or other computer or machine, excluding search engine spiders that comply with the Application’s robots.txt file.  You warrant that you are not prohibited from assenting to this agreement by any preexisting agreement. If you are using the Application on behalf of the third party including but not limited to a business entity, you warrant that you are the authorized and have the authority to bind that third party to the Terms.
    The Application is not a legal service provider.
    The Application only provides a platform for procuring services of the Public Relation Officers (“PRO”) listed on the Application. The information provided by the Application along with the content on the Application related to the services ("Information") is provided for your use and does not constitute any legal service or assistance provide by the Application itself. The Application does not review any information or documents that have been exchanged between yourself and the PRO. We do not review any information provided either by you or the PRO for legal accuracy or sufficiency, draw legal conclusions, provide opinions, or apply the law to the facts of your situation or confirm / authorize / validate the services provided by the PRO.
    Your use of the Services on the Application does not create a relationship between you and the Application nor will the Application be responsible for any services provided by the PRO.
    The Application does not endorse or recommend any PRO nor does it make any warranty as to the qualifications or competency of the PRO.
    Interactions with PRO on the Application
    When you use the Application, you will have the opportunity to initiate contact with a PROs who have registered themselves with the Application (a "Participating PRO(s)"). Participating PRO are neither employees nor agents of the Application. Participating PRO are third-party independent contractors that have agreed to provide limited services to the Application users. However, if you choose to communicate with a Participating PRO through the Application, please note the following:
    •	When you contact a Participating PRO through the Application, he or she may provide you with an initial consultation, review of documents, or answer your questions. Please note that any such interaction is intended to be a starting point for dealing with a service or addressing basic questions related to services and that interaction is strictly between you and the Participating PRO and expressly excludes the Application.
    •	When you contact a Participating PRO through the Application, he or she may ask you for some information regarding you and your legal affairs in order to properly address your questions. By using the Application, you consent to sharing such personally identifying information for the purpose securing services with both the requesting PRO and with Application. Application will have access to any communications submitted through our platform for fulfilment and quality assurance purposes.
    •	When you contact a Participating PRO through the Application, you control the both the duration and depth of the interaction. Any PRO-client relationship formed during the course of that interaction may, at your option, either (i) end when the interaction with the Participating PRO ends, or (ii) continue if you wish to engage the Participating PRO for further services.
    •	If you wish to create a PRO-client relationship with a Participating PRO that extends beyond your use of our application, that relationship will be on whatever terms you establish with the PRO in question. Those terms do not involve the Application and we do not set, control or influence them. For example, the Participating PRO may ask you to sign a formal representation agreement regarding the scope of work they will perform, the cost of their services, and the handling of any out-of-pocket expenses they may incur.
    •	The Application does not receive any share of fees collected by any PRO in our network. In all cases, the Application will not influence or interfere in any way with any PRO's independent professional judgment. Participating PRO reserves the right to refuse to perform services on your behalf in their sole discretion. The Application would not be responsible to hear any grievance in relation to services provided by the PRO.
    •	Application is an information provider and does not endorse or recommend any PRO, including any of the Participating PRO. Application makes no representation or warranty as to the qualifications or competency of any Participating PRO or as to the accuracy or completeness of any Participating PRO's work. Application shall have no responsibility or liability of any kind for any professional services rendered by any PRO you encounter on or through the Application, and any use or reliance on such professional services is solely at your own risk.
    PRO Profiles on the Application
    PRO profiles on the Application should be interpreted as advertisements. While Application strives to provide and to allow Participating PRO to provide useful and correct information regarding PRO and their services, there are some things that we cannot guarantee. Application does not investigate, verify or warrant the accuracy of the information contained in any PRO profile on the Application. Participating PRO are third-party independent contractors solely responsible for the advice they give, the services they provide and the representations about themselves they make. You are solely responsible for assessing the quality, integrity, suitability and trustworthiness of all persons with whom you communicate regarding your service requirements.
    PRO rating reflects Application assessment of a given participating PRO, based upon the information obtained by or submitted to the Application by its users. Someone else's assessment of the same PRO may be very different or be based upon different information. PRO rating is not an endorsement of any particular PRO and is not a guarantee of a PRO's quality, competence, or character. Nor is the PRO rating a predictor of the outcome of any matter in which such PRO is involved. Rather, the PRO ratings are intended to be a starting point to gather information about PRO who may be suitable for your legal needs - but you should not rely solely on the PRO rating in deciding whether to contact or hire any given Participating PRO.
    Ownership and Preservation of Your Documents
    Application does not claim ownership of any documents you either create or upload and store using the Application ("Documents"). You grant permission for Application to use your Documents in connection with providing any services to you. You agree that Application has no responsibility or liability for deleting or failing to store any content maintained or uploaded by the Application.
    Consent to Receive Emails
    By creating an account, you agree that you may receive communications from Application, such as newsletters, special offers, and account reminders and updates. You also understand that you can remove yourself from these communications by clicking the "Unsubscribe" link in the footer of the actual email.
    Acceptable Use of Communications Services
    The Application includes a large number of what are collectively called "Communications Services." These include services such as live chats, question and answer products, callback requests and other message services. You agree to use the Communication Services only to post, send, and receive messages or materials proper to and related to the particular Communication Service. When using a Communication Service, you agree that you will not do any of the following:
    •	Defame, abuse, harass, stalk, threaten or otherwise violate the legal rights of others.
    •	Publish, post, upload, distribute or disseminate any names, materials, or information that is considered inappropriate, profane, defamatory, infringing, obscene, indecent, or unlawful.
    •	Create a false identity, represent yourself as someone else, or otherwise falsify or delete in an uploaded file any significant attributions or notices.
    •	Upload corrupted files, files that contain viruses, or any other files that may damage the operation of another's computer.
    •	Advertise, offer to sell, or offer to buy anything for business purposes except to the limited extent any particular Communication Service specifically allows such activity.
    •	Restrict or inhibit any other user from using and enjoying the Communication Services.
    •	Harvest or otherwise collect personally identifiable information about others, without their consent.
    •	Violate any code of conduct or other guidelines, which may be applicable for any particular Communication Service.
    •	Violate any applicable laws or regulations.
    Although Application has no obligation to monitor the Communication Services, we reserve the right, in our own discretion, to review and remove materials posted to a Communication Service, in whole or in part. Application reserves the right to disclose any materials posted, information or activity as necessary to satisfy any applicable law, regulation, legal process, or governmental request.
    No Unlawful or Prohibited Use
    You can only use the services of the Application if they do not conflict with or violate the laws of your jurisdiction(s). The availability of the Application in your jurisdiction(s) is not an invitation or offer by Application to access or use the Application. By using the Application, you accept the sole responsibility that you or any family member's use of or access to the Application does not violate any applicable laws in your jurisdiction(s). To enforce this provision, Application reserves the right to refuse membership, or suspend or terminate your account immediately and without prior notice at our sole discretion.
    The following are specifically excluded or prohibited:
    •	Use in connection with any legal matter that is frivolous, immaterial or illegal in nature, as determined by Application or the Participating PRO in their sole discretion;
    •	Use in connection with any legal matter involving an alleged violent crime;
    •	Use in connection with any legal matter that, as determined by the Participating PRO in his or her sole discretion, lacks sufficient merit to warrant pursuit, or that has been raised an excessive or unreasonable number of times without a change in circumstances;
    •	Use in connection with any legal matter that directly or indirectly involves Application or any of its affiliates, directors, agents, employees, or other Application service providers;
    You may not hack, "scrape" or "crawl" Mandobi Application whether directly or through intermediaries such as spiders, robots, crawlers, scrapers, framing, iframes or RSS feeds, or otherwise access or attempt to access any information Application has not intentionally made available to you on the Application via subscription. Your use of the Application does not entitle you to resell any its content without prior express written consent from Application.
    Services for Consumers and Refund Policy
    Application is not a legal service provider or a service provider and does not provide any services. The Application is merely a facilitator by providing and allowing consumers to buy listed services from Participating PROs. The Application provides a number of methods by which you can purchase services or have a direct, confidential discussion of your issues with a Participating PRO. Although some of these methods involve Application processing a transaction on your behalf, in all instances, Application is simply the intermediary in such transactions.
    You are liable for paying the Participating PRO for the services delivered. Application has no liability, either primarily or secondarily, for paying the service provider other than as an agent on your behalf. The fees you pay for such services are charged by the service provider and passed through to the service provider once services have been rendered.
    If for some reason the Participating PRO you purchased the service from via the Application could not provide you the purchased service, you can always submit a support request detailing the issue. A Application support representative will review your case and assist you with the refund request or will suggest you another service provider.
    Any relationship formed as a result of such services is between you and the PRO you hired — not between you and Application. Furthermore, you understand that Application cannot be held responsible for the quality or accuracy of any information or services provided by PRO you connect with via the Application.
    It is solely the responsibility of service providers to ensure that any information or advertisements they post or place on the Application, and any communications they may have with prospective clients through the Application, fully complies with all applicable laws and rules of professional conduct, including those concerning the unauthorized practice of law and those regulating the form, manner or content of communications with clients, advertising, or other matters.
    User Account
    Your User Account is protected by a username and password. You acknowledge that you are solely responsible for maintaining the security and confidentiality of your username and password and for any access to your account, whether authorized or unauthorized. In the event your account is accessed without your authorization, you agree to immediately provide notice to Application.
    Application reserves the right to revise its Fees, including by increasing or adding new Fees, at any time on ten (10) days’ notice. Such notice may be sent to you by email to your most recently provided email address or posted on the Application or by any other manner chosen by Application in its commercially reasonable discretion. You will be deemed to have received any such notice that is posted on the Application on the day it was posted. Your use of the User Account after the ten (10) day notice period constitutes your acceptance of the new or revised Fees. If you do not agree to the revised Fees, you may cancel your subscription by sending us a request.
    To ensure uninterrupted service, all subscriptions are renewed automatically. You hereby authorise Application to charge subscription Fees for the renewal period to the credit card account on file. All subscriptions are renewed at the subscription level in effect at the time the then-current subscription term ends. You may cancel the subscription at any time by sending us a request.
    If you cancel after your subscription renewal date, you will not receive a refund for any amounts that have been charged. Your cancellation will be effective at the end of your then-current subscription period, subject to applicable law, and you may use the User Account until your cancellation is effective (unless your access is suspended or terminated as set forth below).
    Application may deny you access to all or any part of the Application or terminate/downgrade your User Account with or without prior notice if you engage in any conduct or activities that Application determines, in its sole discretion, violate this Terms or the rights of Application or any third party, or is otherwise inappropriate. In this case, all Fees paid or accrued in connection with your User Account are non-refundable, and Application will not prorate any Fees paid for a subscription that is terminated before the end of its term.
    If you have been charged by mistake or there has been an error in billing, please submit a support request detailing the issue. A support representative will review your case and assist you with your refund request.
    License Grant
    Subject to your compliance with these Terms, you are hereby granted a non-exclusive, limited, non-transferable, revocable license to use the Application as we intend for them to be used. As a registered Application user, you are licensed to keep, for your own personal records, electronic or physical copies of documents you have created on the Application. Any rights not expressly granted in these Terms are reserved by Application.
    When you transmit user content on the Application, you hereby grant Application and its affiliates a non-exclusive, royalty-free, perpetual, irrevocable and fully sublicensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display any such content, including throughout the world in any media. If you submit feedback or suggestions about the Application, we may use your feedback or suggestions without obligation to you.
    Resale or unauthorized distribution of materials downloaded from the Application is strictly prohibited. Use of these materials is for your personal or business use. Any resale or redistribution of our materials requires the express, written consent of Application.
    Intellectual Property Rights
    Application retains all right, title and interest in and to its products and services, including, without limitation, software, images, text, graphics, illustrations, logos, service marks, copyrights, photographs, videos, music, and all related intellectual property rights. Except as otherwise provided in this agreement, you may not, and may not permit others to: (i) reproduce, modify, translate, enhance, decompile, disassemble, reverse engineer or create derivative works of any of our products and services; (ii) sell, license, sublicense, rent, lease, distribute, copy, publicly display, publish, adapt or edit any of our products and services; or (iii) circumvent or disable any security or technological features of our products and services.
    Disclaimer of Representations and Liability
    The information, software, products, and services made available through the Application may include inaccuracies or typographical errors. Application and/or its suppliers may at any time make improvements or changes to the Application. Information received via the Application should not be relied upon for personal, medical, legal, or financial decisions. You should consult an appropriate professional for specific advice tailored to your situation. In short, your use of the Application is at your own risk.
    To the fullest extent permitted by law, Application and its affiliates, suppliers and distributors make no warranties, either express or implied, about the Application, which is provided “As is”. We also disclaim any warranties of merchantability, fitness for a particular purpose and non-infringement.
    Indemnity and Release
    You agree to release, indemnify and hold Application and its affiliates and their respective officers, employees, directors and agents harmless from any and all losses, damages, expenses, including reasonable PRO' fees, rights, claims, actions of any kind and injury (including death) arising out of any third party claims relating to your use of the Application, your violation of these Terms or your violation of any rights of another.
    Limitation of Liability
    To the fullest extent permitted by law, in no event shall Application or any of its affiliates, suppliers and distributors, or any of their respective directors, employees and agents, be liable for any special, indirect or consequential damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from (a) the outcome of any legal matter; (b) your access to or use of or inability to access or use the Application; (c) any conduct or content of any third party relating to the Application; or (d) unauthorized access, use or alteration of legal information.
    Modifications
    Application may, from time to time, modify, limit, change, discontinue, or replace the Application. Application reserves the right to modify, limit, change, discontinue, or replace the Application in its sole and absolute discretion. In the event Application modifies, limits, changes, or replaces the Application, your use of the Application after said modification, limitation, change, or replacement constitutes your manifestation of assent to the modification, limitation, change, or replacement. By using or continuing to use or access the Application after any revisions have come into effect, you agree to be bound by the revised Terms.
    Entire Agreement
    These Terms constitute the entire agreement between you and Application with respect to the subject matter of these Terms, and supersede and replace any prior version of the Terms. These Terms create no third-party beneficiary rights.
    Questions & Contact Information
    Mandobi
    """,
      style: TextStyle(
          fontFamily: FontUtils.poppinsRegular,
          fontSize: Fontsizes.size10,
          color: ColorUtils.black),
    );
  }
}
